# Generated by Django 3.0.5 on 2020-04-14 00:41
# migración manual para agregar registros a la tabla category
# que será usado como categoría predeterminada para los post registrados en la bd

from django.db import migrations

def insert_default_category(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    Category.objects.create(name= 'Default category', description= 'Default category')

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200413_1930'),
    ]

    operations = [
        migrations.RunPython(insert_default_category)
    ]
