# Generated by Django 3.0.5 on 2020-04-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200413_0929'),
        ('blog', '0008_category_is_active'),
    ]

    operations = [
    ]
